{% set pkg_name = 'rattler_build_test' %}
{% set version = '0.0.2' %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: "SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} pip install --no-deps --no-build-isolation --ignore-installed ."
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  run:
    - numpy >=1.22,<1.25
  build:
    - pip
    - setuptools
    - setuptools_scm
test:
  imports:
    - "{{ pkg_name }}"
